spring.application.name=edupath-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/edupath
spring.datasource.username=postgres
spring.datasource.password=Mohit@1718

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true